GET http://localhost:3000 HTTP/1.1
###
GET https://localhost:3000 HTTP/1.1
###
GET https://localhost:3000/test HTTP/1.1
###
GET https://localhost:3000/api/departments HTTP/1.1
###
POST https://localhost:3000/api/posts HTTP/1.1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NTFkMzVlM2UzNWQyZGY5NGZlNzBkMzIiLCJpYXQiOjE2OTY5NzMyMDQsImV4cCI6MTY5NzA1OTYwNH0.vQ34YTemjzvF8FVce9hNL-S1Bn7hAVrlBfNAflANIKA
content-type: application/json

{
    "department": "Electric",
    "content": "we still still have no power"
}

###
GET https://localhost:3000/api/posts HTTP/1.1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NTFkMzVlM2UzNWQyZGY5NGZlNzBkMzIiLCJpYXQiOjE2OTY5NzMyMDQsImV4cCI6MTY5NzA1OTYwNH0.vQ34YTemjzvF8FVce9hNL-S1Bn7hAVrlBfNAflANIKA
###
DELETE https://localhost:3000/api/posts/651c63b8da6c48e170b97e92 HTTP/1.1
###
GET https://localhost:3000/api/posts/651c62a6dfe2094055eaf760 HTTP/1.1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NTFkMzVlM2UzNWQyZGY5NGZlNzBkMzIiLCJpYXQiOjE2OTY5NzMyMDQsImV4cCI6MTY5NzA1OTYwNH0.vQ34YTemjzvF8FVce9hNL-S1Bn7hAVrlBfNAflANIKA
###
POST https://localhost:3000/api/users/register HTTP/1.1
content-type: application/json

{
    "username": "st10081966",
    "email": "st10081966@vcconnect.edu.za",
    "name": "Adam",
    "surname": "Swain",
    "password": "Testing123"
}

###
POST https://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "username": "st10081966",
    "password": "Testing123"
}
###
POST https://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "username": "st10081966",
    "password": "Testing124"
}
